pkgdown/_pkgdown.yml

This PR fix the wrong url in the pkgdown configuration file.

fix: update url for the pkgdown site

---

README.md

The example had parameters = FALSE, but the default child documents contained a reference to a parameter as an example for use in-text. This will be fixed by setting parameters = TRUE (default), but also by removing the line in the file.
We are redesigning this example and will provide an example folder where users can see the product of create_template, convert_output, and rendering of the quarto document (not in this PR)

fix(README): fix example 

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/ISSUE_TEMPLATE/question.yml
.github/pull_request_template.md
.github/workflows/pr-checklist.yml

@Schiano-NOAA and @sbreitbart-NOAA, This PR adds a few issue templates from FIMS to this repo. The goal is to provide instructions for anyone submitting an issue or PR, as well as for those reviewing pull requests. Please let me know if any of the templates or checklists seem excessive for this repo.
- add bug report template
- add feature request template
- add question template
- add pull request template
- add PR checklist

add issue templates

---

inst/resources/formatting_files/_titlepage.tex

* Added alt text to cover page's US Dept of Commerce seal
* Writing a line of LaTeX
* No

build: added alt text to cover page's US Dept of Commerce seal

---

inst/resources/formatting_files/_titlepage.tex

* Fixing the cover's USDC logo to properly contain no alt text. My last commit wasn't written properly. There shouldn't be alt text for this logo because it's purely decorative (an "artifact").
* Updated (corrected) latex syntax
* No

fix: updated syntax for cover USDC logo

---

R/create_template.R
R/utils_tex.R

* Standardizes the size of the cover image
* adjusts spp_image argument so users can add a path to the image and it uses it properly #62
*add spp image that is outside of the template
*copy image file to working folder and extract image file name
*no

fix(cover image)

---

DESCRIPTION
R/add_theme.R
tests/testthat/test-add_theme.R

* Removing dependency from package to allow download of package
* Comment out use of `nmfspallete` in add_theme function and its tests
*Remove `nmfspallete` from dependencies in DESCRIPTION
*yes. this will now allow users to properly plot with the nmfs colors; however, we have also temporarily removed instances of nmfspallete from `satf`

Remove nmfspallete from dependencies temporarily

---

inst/resources/asar_references.bib

* Fixes an incorrect reference in asar_references.bib. Sorry if this PR is to the wrong branch or you prefer a different process to edit the .bib file.
* I copied info from source URL which @okenk and @chantelwetzel-noaa tracked down. This matters more than you would expect because the document is a key data source that we have not consistently included in production assessments. Having an accurate reference will improve access to the report and make it more likely that all catch is accounted for.
* Definitely not.

fix to incorrect reference in .bib file

---

R/create_template.R
man/create_figures_doc.Rd
man/create_tables_doc.Rd
man/create_template.Rd

- https://github.com/nmfs-ost/asar/issues/144
- Fix `create_template` so that rda files can be added as input, if already created, OR generated if model results are included as an argument.
- Update documentation
* in `create_template`, changed the `exp_all_figs_tables()` rda_dir argument from subdir to rda_dir. This changes the workflow so that the rda_files folder is always placed in rda_dir, not in the report folder. The issue was that the captions_alt_text.csv file was always being created in rda_dir, but `exp_all_figs_tables()` within `create_template()` was breaking because captions_alt_text.csv wasn't ever within the "report" folder. I chose to keep the rda_files folder in the rda_dir, instead of the report folder, because sometimes the user will be providing their own rda_files …

Fix(create_template)

---

R/create_template.R
inst/resources/asar_references.bib
inst/templates/skeleton/06_acknowledgments.qmd
inst/templates/skeleton/07_references.qmd

* References are placed in their proper section
* new citation in bibliography for {asar}
* acknowledgement for use of {asar} in respective section
**Intended to be placed into main as a hotfix rather than with a new feature**
* Uncomment placement notation in references.qmd
* added new citation to .bib file
* added new statement line to acknowledgements.qmd
*no

Fix bug with references rendered in wrong location

---

R/create_template.R

* Adding message before exp_all_figs_tables() is run in create_template() as per Sam's request https://github.com/nmfs-ost/stockplotr/pull/70#issuecomment-2770355794
* Messages
* No

Add clarifying message before create_template() runs exp_all_figs_tables()

---

inst/templates/skeleton/11_appendix.qmd

update(appendix): change notation before section so it starts as A. B, ect instead of 11. appendix, restarts numbering of tables and figures
* Number appendix rather than add it as additional number in outline
* reset numbering of tables and figure
* add latex code before appendix section
* no

Add notation for appendix rendering

---

R/add_alttext.r

* fix(add_alttext): only add alttext for figures in loop for fxn
* reduced objects that are run through the loop
* no

Fix issue with add_alttext

---

.github/workflows/call-build-pkgdown.yml
.github/workflows/call-doc-and-style-r.yml
.github/workflows/call-r-cmd-check.yml
.github/workflows/call-spell-check.yml
.github/workflows/call-update-pkgdown.yml

Hello, this repository depends on [ghactions4r](https://github.com/nmfs-fish-tools/ghactions4r). The ghactions4r repository will be moving from https://github.com/nmfs-fish-tools/ghactions4r to https://github.com/nmfs-ost/ghactions4r on **May 16, 2025 between 9 am and 12 pm pacific**. When the move happens, all GitHub actions workflows that reference a ghactions4r workflow will break.
**To keep actions from breaking, please take a look at your github action YAML files (located under .github/workflows in your repository) and change any references of nmfs-fish-tools/ghactions4r (the old organization) to nmfs-ost/ghactions4r (the new organization) between now and May 16**. This has been done for you in this pull request, so it can simply be merged in.
If you would like to make the changes …

update ghactions4r workflow location

---

R/create_template.R
R/create_yaml.R

* fix(create_yaml): authorship formatting messed up when rerender=TRUE
* Removed trailing space in extraction code of authorship in create_yaml
* removed separating space in create_template authorship section
* no

Fix issue when rerendering and adding author creates invalid spacing in yaml

---

R/create_template.R
tests/testthat/test-ID_tbl_width_class.R

* Proceed with rerender_skeleton if session is not interactive, as per https://github.com/nmfs-ost/asar/issues/205
* Test if session is interactive. If not, question1 = "y"
* No

Proceed with rerender_skeleton if session is not interactive

---

.github/workflows/call-calc-cov-summaries.yml
.github/workflows/call-create-cov-badge.yml

* See #235. Adds quarto to 2 coverage github actions, but fixes the mistake I made in #235 of doing my work off of main instead of dev!
* Also adds a build trigger so that code coverage summaries will show up on pull requests made to dev (there should be an example on this PR shortly!)
*
*

Add quarto dependency to 2 github actions

---

R/create_template.R
inst/resources/formatting_files/_titlepage.tex

* Combines city and state in the title page so it renders - temporary fix since we will be altering authorship approach soon anyway
* new notation in _titlepage.tex and change to authorship portion in create_template
* no

Fix author affiliation in title page

---

.github/ISSUE_TEMPLATE/affiliation_request.yml

add new issue template for users when affiliation of a collaborator is missing
* Create a new issue template so that users can request to add in a new affiliation to our database
* I wonder how hard it would be to create entries for this then make an action that once we approve it, it will automatically add to the database
* New template yml in templates folder
* no

New issue template - affiliation

---

R/create_template.R

* Translate the parameters loaded in the yaml to a chunk for shorter in-text references for the user
* added new chunk to the outline with parameters loaded as objects
* no

Add params chunk to outlne

---

R/create_figures_doc.R
R/create_tables_doc.R

* Allow for relative paths in create_tables_doc and create_figures_doc
* using `deparse(substitute())` to parse path
* No

Allow for relative paths in create_tables_doc and create_figures_doc

---

R/create_figures_doc.R
R/create_tables_doc.R
vignettes/faqs.Rmd

* Reset figure and table doc paths to absolute, reverting https://github.com/nmfs-ost/asar/pull/297
* Add documentation explaining decision
*
* No

Fix filepaths

---

R/add_tagging.r
R/utils_tex.R
inst/resources/formatting_files/in-header.tex

* Remove latex warning when tagging document
* removed notation for one package that gets loaded in from quarto
* add in soul package
* no

Remove latex warnings on tagging

---

R/add_accessibility.R
R/add_alttext.r
R/add_tagging.r

…e name of the previous pdf
* Add in the ability to keep the same name as the pdf file when rename = NULL
* This PR is complete and was done during the NSAP code cleanup
* Add new call on render at the end of the function
* no

[Feature]: rename the final pdf final after adding a11y

---

R/create_template.R

* Change code for add region abbreviation in the report name (GA -> GOA)
* used stringr instead of gsub
*no

Fix region abbreviation in report name

---

R/create_template.R

* remove duplicated code when custom sections are explicit causing improper formatting
* address issue #350 
* removed duplicated code in the function where custom sectioning is handled
* yes, this will need to be rebased throughout all branches

Fix bug when making custom template
