R/add_chunk.R
tests/testthat/_snaps/add_chunk.md
tests/testthat/test-add_chunk.R
tests/testthat/test-create_template.R

This PR addresses issue #28 and adds unit tests for create_template() and add_chunck()

test: add tests for create_template() and add_chunk()

---

README.md

Changed library from ASAR to asar so example code worked if copy/pasted from readme into user console

changed library in readme example (ASAR --> asar)

---

DESCRIPTION
man/create_template.Rd
tests/testthat/test-add_theme.R
tests/testthat/test-create_template.R

- add gt to the Imports section in DESCRIPTION and reorder package listings
- use ggplot2:: to access specific functions from ggplot2
- update the path the assessment reports for testing purposes

fix failed GHA tests on main branch

---

tests/testthat/test-add_chunk.R

* Fix the add_chunk() tests as described in PR https://github.com/nmfs-ost/asar/pull/55
* Uncommented the add_chunk() tests and didn't make any other changes
* The GHA tests have passed
* No

fix add_chunk() tests

---

R/create_template.R

* shorten chunk labels in create_template.R
* removing preceding numbers
* no

Shorten create_template chunk labels

---

README.md

Update(README.md): add pak installation instructions

---

vignettes/accessibility_guide.Rmd

* Fixing bug in https://github.com/nmfs-ost/asar/issues/93#event-15562576631
* Adding a "verbatim" code chunk around faulty chunk
* No

fixed bug in a11y vignette

---

R/create_template.R
inst/resources/asar_references.bib
man/create_template.Rd
tests/testthat/test-create_template.R

*Add in a default bib file
*Add default into argument and replace the pathing with the file - also copies over the entered file if it is not the default
*No, but does solve issue #70

Default bib

---

DESCRIPTION

* change testthat's parallel option from true to false, because having parallel on was causing the ubuntu github action to fail
* change one line in the description file. We expect the github actions to all pass on this branch.
* no

change testthat  parallel option to be false

---

R/create_figures_doc.R
R/create_tables_doc.R
R/create_template.R
man/create_figures_doc.Rd
man/create_tables_doc.Rd
man/create_template.Rd

* Updating multiple scripts in asar to harmonize changes to individual figure and table-plotting fxns in satf (and satf::export_all_figs_tables) https://github.com/nmfs-ost/satf/pull/39
* Updating create_figures_doc, create_tables_doc, and create_template to work with new fxn arguments and include new fxns when creating figures and tables
* No

Integrate new fxns

---

R/create_template.R

*Add a check so if convert_output=TRUE, it looks for a previously converted dataframe with the same label - help prevent having to rerun the convert_output code if the template needs to be remade
*Add if statement before convert_output function in create_template
*no

Add check when convert_output = TRUE

---

README.md
vignettes/accessibility_guide.Rmd
vignettes/faqs.Rmd
vignettes/manual.Rmd
vignettes/markdown_notation.Rmd
vignettes/regional_workflows.Rmd

*moving the changes into the dev1.1 into dev after dev was fixed on 18-01-25
*
*

Merge newer dev branch into old

---

R/create_template.R
R/format_quarto.R
inst/resources/formatting_files/theme.scss

* Allows generated skeleton to render to html
* added the functionality in format_quarto and updated create_template to copy in the theming files to the support_files folder**
*no

Add functionality for formatting to html

---

inst/resources/affiliation_info.csv
inst/resources/authorship.csv

* Updating authorship csv files according to a comment in issue #19 
* Added middle initial for two authors as well as a new address for CAFW
*no

Update authorship csv files

---

R/convert_output.R

* Fixes the issue where 0 in R0 was removed from the label name in BAM converted output and placed in age column
* Adjusted the treatment of labels from "parms" module_name to fix this issue
* no

Fix translation of R0 parameter from BAM in convert_output

---

DESCRIPTION
R/add_alttext.r
R/create_figures_doc.R
R/create_tables_doc.R
R/create_template.R
R/zzz.R
README.md
inst/WORDLIST
man/add_alttext.Rd
man/create_figures_doc.Rd
man/create_tables_doc.Rd
man/create_template.Rd
tests/testthat/test-add_accessibility.R
tests/testthat/test-add_alttext.R
vignettes/accessibility_guide.Rmd
vignettes/convert_output_details.Rmd
vignettes/custom-figs-tabs.Rmd

* Updating asar's functions to work with stockplotr's, after 1) updates to exp_all_figs_tables and 2) name change from satf to stockplotr.
* Adding in the new args to create_template's exp_all_figs_tables, and removing old, and replacing satf with stockplotr
* Yes

Make asar compatible with stockplotr

---

DESCRIPTION

* Reduce dependencies
*Move packages that are not directly references in a fxn to suggests
*no

update DESCRIPTION to move unncessary dependencies to suggests

---

R/add_section.R
R/create_template.R
tests/testthat/test-add_section.R
tests/testthat/test-create_template.R

* Fixes an issue where when using mostly all custom parts of the template it sends an error
* Made adjustments to add_section and create_template functions in order to fix this
* no

Hotfix custom sections

---

R/add_section.R

* Produce unique labels for custom sections' example chunks
* Small change to label name in add_section()
* No

Produce unique labels for custom sections' example chunks

---

R/add_alttext.r

reflect changes to alttext fxn pushed into dev and pre-reviewed

---

inst/templates/nemt/01_executive_summary.qmd

* Add special comments questions to NEMT template executive summary
* See above
* No

Add special comments questions to NEMT template executive summary

---

inst/templates/skeleton/06_acknowledgments.qmd

* new text in acknowledgements skeleton suggested by #230 
* new sentence
* no

updated reference to asar in default acknowldgements per #230

---

vignettes/accessibility_guide.Rmd
vignettes/faqs.Rmd

* New documentation explaining how to use acronyms and the glossary
* Editing vignettes
* No

Glossary documentation

---

R/create_citation.R
inst/resources/formatting_files/in-header.tex

* Add page count to citation
* Add latex notation suggested from #108 - `\pageref{LastPage}{}`
* no

Add page count to citation

---

R/format_quarto.R

* Comment out option and add stop when docx is selected (not currently functional)
* Set defaults in replace of NULL in all functions
* see above
* No

Address assigned items in "format_quarto" section of cleanup plan

---

R/convert_output.R

*assigns era categories for output converted from BAM model output
* manipulated era at the end following start and end year parameters
* use naming conventions in era following SS3
* no

add era into final df conditionally

---

R/add_alttext.r
R/add_base_section.R
R/add_section.R
R/add_tagging.r
R/convert_output.R
R/create_citation.R
R/create_figures_doc.R
R/create_tables_doc.R
R/create_template.R
R/create_yaml.R
R/export_object.R
R/format_quarto.R
R/remove_draft.R
R/utils.R

* Substitute messages and warnings with cli package versions
* see above
* No

Substitute messages, warnings, and stops with cli

---

DESCRIPTION
R/create_figures_doc.R
R/create_template.R
tests/testthat/test-create_citation.R
tests/testthat/test-create_figures_doc.R
tests/testthat/test-create_tables_doc.R
tests/testthat/test-create_template.R
tests/testthat/test-export_split_tbls.R

* Fixing code/tests as needed to align with package revamp
* changing majority of tests as needed
* no

Cleanup pkg tests

---

DESCRIPTION
pkgdown/extra.css

* Adding BugReports link to DESCRIPTION
* Removing mentions of nmfspalette (@Schiano-NOAA we don't need those, do we? Because the function that applies nmfspalette theming (add_theme) is in stockplotr
*
*

Remove nmfspalette from asar

---

R/convert_output.R
man/convert_output.Rd

* add back in save option to convert_output -- default is now rda
* save when save_dir is not NULL
* no

Option to save in convert_output

---

R/convert_output.R
R/create_figures_doc.R
R/create_tables_doc.R
R/create_template.R
inst/WORDLIST
man/convert_output.Rd

* Add back features from https://github.com/nmfs-ost/asar/pull/251 that were removed once model_results was removed from create_template (now, it's being added back in again)
* Adding back original code with some improvements
* No

Metadata messaging and file creation

---

README.md

* Updating missing change to readme example
* added save_dir to conout and added load in of conout to model_results in create_template example
* no

[Fix]: README example 

---

README.md

* Remove sentence from readme stating stockplotr is a dependency
*
*

Remove sentence from readme stating stockplotr is a dependency

---

R/create_template.R

* We added an if statement that assigns the `params$region` value where existing region value is NULL
* Added an if statement as directed by Issue 330: https://github.com/nmfs-ost/asar/issues/330
* No

Addregion dev

---

R/ID_tbl_width_class.R
R/add_authors.R
R/convert_output.R
R/create_figures_doc.R
R/create_tables_doc.R
R/render_lg_table.R
R/utils.R

* Addresses issue #324 
*  removes final return(x) from function
* No

remove return(x) from end of function

---

README.md

Issue #317: Added some text regarding the code of conduct to the existing readme. Also, included a link to the FIMS code of conduct.
* Added text for a code of conduct and linked out to existing FIMS code of conduct
* Added text to existing ReadMe file
* No

Codeofconduct dev

---

vignettes/faqs.Rmd

* Improvements to FAQ vignette as per [Kathryn and Len's suggestions](https://docs.google.com/document/d/1sfG3NqDoPND6B2A1wdWsb0Ftnfga-eDePSsPQdbWflA/edit?tab=t.0#heading=h.g18p6l1l2lc3)
* Edits to FAQ vignette
* No

Improve FAQ vignette

---

R/create_figures_doc.R
R/create_tables_doc.R
R/create_template.R

* Ensure headers for figures/tables docs aren't duplicated in some circumstances
* Fixing bugs
* No

HOTFIX: Fix sometimes duplicative headers
